package monkeypuzzle.entity.sqlite;

import java.util.List;

import monkeypuzzle.io.parser.sqlite.dynamicproxy.SqlField;
import monkeypuzzle.io.parser.sqlite.dynamicproxy.SqlTable;

/** Autogenerated from Library/Notes/notes.db */
public interface Notes extends List<Notes.Note>
{

	@SqlTable(tableName = "NOTE")
	public interface Note
	{
		@SqlField("creation_date")
		public int getCreationDate();

		@SqlField("summary")
		public String getSummary();

		@SqlField("title")
		public String getTitle();
	}

	@SqlTable(tableName = "NOTE_BODIES")
	public interface NoteBodies
	{
		@SqlField("note_id")
		public int getNoteId();
	}
}