package monkeypuzzle.entity.status;

import monkeypuzzle.io.parser.plist.dynamicproxy.PListAnnotationEntry;

/** Autogenerated from Status.plist */
public interface Status
{
	@PListAnnotationEntry("Backup Success")
	public java.lang.Boolean getBackupSuccess();
}